import {HashMap} from "./hash_map.mjs";

const test = new HashMap() // or HashMap() if using a factory

test.set('apple', 'red')
console.log(test.entries())
test.set('banana', 'yellow')
console.log(test.entries())
test.set('carrot', 'orange')
console.log(test.entries())
test.set('dog', 'brown')
console.log(test.entries())
test.set('elephant', 'gray')
console.log(test.entries())
test.set('frog', 'green')
console.log(test.entries())
test.set('grape', 'purple')
console.log(test.entries())
test.set('hat', 'black')
console.log(test.entries())
test.set('ice cream', 'white')
console.log(test.entries())
test.set('jacket', 'blue')
console.log(test.entries())
test.set('kite', 'pink')
console.log(test.entries())
test.set('lion', 'golden')
console.log(test.entries())
test.set('moon', 'silver')
console.log(test.entries())
